apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins-prod
namePrefix: prod-
resources:
  - ../../base
  - jenkins-prod-sealedsecret.yaml
patchesStrategicMerge:
  - patches.yaml
configMapGenerator:
  - name: jenkins-config
    behavior: replace
    files:
      - jenkins.yaml=prod-jenkins.yaml
