# overlays/jenkins-dev/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins-dev
spec:
  ingressClassName: nginx
  rules:
  - host: jenkins.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-jenkins
            port:
              number: 8080