apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-plugins
data:
  plugins.txt: |
    # Core requirements
    workflow-aggregator:latest
    credentials:latest
    ssh-credentials:latest
    git:latest
    kubernetes:latest
    # Configuration as Code
    configuration-as-code:latest
    configuration-as-code-support:latest
    # Optional useful plugins
    pipeline-stage-view:latest
    job-dsl:latest
