apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
  - web-deployment.yaml

patchesStrategicMerge:
  - controller-patch.yaml
  - web-serviceaccount.yaml
  - web-rbac.yaml
